### ISSUE TITLE
vlan 1.9 download fails / gone

### ISSUE THREAD

**Issue by hollaho** [slashbeast/better-initramfs#32]
See

>>> Fetching vlan.1.9.tar.gz ...
--2015-04-02 02:23:08--  http://fossies.org/linux/misc/vlan.1.9.tar.gz
Auflösen des Hostnamen »fossies.org«... 78.46.58.28
Verbindungsaufbau zu fossies.org|78.46.58.28|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 410 Gone
2015-04-02 02:23:09 FEHLER 410: Gone.

>>> Command 'wget http://fossies.org/linux/misc/vlan.1.9.tar.gz -O /usr/src/better-initramfs/bootstrap/distfiles/vlan.1.9.tar.gz.tmp' failed.
>>> Build failed: 'vconfig'.

**Comment by hollaho** [comment]
seems to be moved to

http://fossies.org/linux/misc/old/vlan.1.9.tar.gz

**Comment by slashbeast** [comment]
I've rehosted this file so it shoudn't happen again. Fixed in devel 3079e57.
