### ISSUE TITLE
Include additional kernel modules

### ISSUE THREAD

**Issue by s-hell** [slashbeast/better-initramfs#40]
How can i include additional kernel modules? For example the nvidia module.
All monitors are connect to one nvidia graphic card. So it would be nice to include this module in my initramfs image.

**Comment by slashbeast** [comment]
No feature for kernel modules loading exist currently. This said, you can still add them into initramfs and use `insmod` to load them. Linux support multiple initramfs images so you can have one generic and one kernel specific with modules.

The insmod calls can be placed in any hook, check the README about the hooks.

**Comment by coffnix** [comment]
> No feature for kernel modules loading exist currently. This said, you can still add them into initramfs and use `insmod` to load them. Linux support multiple initramfs images so you can have one generic and one kernel specific with modules.
> 
> The insmod calls can be placed in any hook, check the README about the hooks.

how?? how to gen a new initrd with modules only, and how to set insmod? help, please....

**Comment by slashbeast** [comment]
Can you describe what is the end result that you want to get? Then I can guide you somehow.

**Comment by slashbeast** [comment]
You just need to prepare a cpio archive with those modules and add it into your bootloader, each bootloader have different syntax for initramfs images, or add your modules into sourceroot/ and then have single image. However, if you run Funtoo you should've add those drivers into your kernel and not bother with using a initramfs to load them, unless they do need firmware that you do not want to place inside initramfs, for example iwlwifi are one of those that I rather not have builtin.

So, just builtin those drivers and it will work much better for you.

**Comment by coffnix** [comment]
okay, i will generate a new initrd file using cpio, contain only /lib/modules file.... 
how to modify your initramfs to add support to insmod? to load modules using your initram? is possible? not?

**Comment by slashbeast** [comment]
Everything has been already answered in this issue, there's a system of hooks that one can use to load modules, I am not going to write a step by step guide that you will just paste into shell and get it working as that would be far too complicated, especially when you said you have even USB as module, meaning a some sort of a autoloading would be needed to detect the right modules for hardware and not load every single .ko file.

If you cannot figure out how to do it yourself I think it would be by far better if you rebuild your kernel to include those modes as builtin part not a separated modules, this will remove the whole class of your problems.

**Comment by coffnix** [comment]
i not found any doc about HOOKS, please, send me

**Comment by slashbeast** [comment]
https://github.com/slashbeast/better-initramfs#hooks
