### ISSUE TITLE
ftp.kernel.org

### ISSUE THREAD

**Issue by knightgats** [slashbeast/better-initramfs#41]
Hello slash ! How you doing!? Hope very well ! 

util-linux-2.21.2.tar.bz2 is no longer available through ftp.kernel.org and the script need to be updated to 

https://www.kernel.org/pub/linux/utils/util-linux/v2.21/util-linux-2.21.2.tar.bz2

Thanks

**Comment by slashbeast** [comment]
Thank you for letting me know.

I should finish the migration to Alpine Linux sysroot and the support for non-root building and setup some real CI for this project so it could be built on daily basis and catch such issues.

**Comment by slashbeast** [comment]
Fixes pushed, btw.
