### ISSUE TITLE
Dropbear download failed

### ISSUE THREAD

**Issue by s-hell** [slashbeast/better-initramfs#44]
> Command 'wget http://matt.ucc.asn.au/dropbear/releases/dropbear-2015.71.tar.bz2 -O /root/better-initramfs/bootstrap/distfiles/dropbear-2015.71.tar.bz2.tmp' failed.                                                                                                         
> Build failed: 'dropbear'.                                                                                                                                       

Besides this, this is a very old Version...

**Comment by s-hell** [comment]
Works, but still an old version.

**Comment by slashbeast** [comment]
Yeah, I will update that this weekend. I still have not finished migration to sysroot with Alpine and musl, and I also need to re-write build system for that.

**Comment by slashbeast** [comment]
devel branch updated with new dropbear. I will merge it with master after I update rest of the tools and test it somehow.

**Comment by slashbeast** [comment]
@s-hell I migrated nearly everything to Alpine and got a successful boot with dmcrypt+lvm here. I will update devel branch today or tomorrow that will build using Alpine Linux 3.7.0 (with musl) as well as rehost everything on bitbucket. All versions has been updated to very last releases. You can follow progress on `alpine-migration` branch.
