### ISSUE TITLE
A very cool project - PPA for ubuntu?

### ISSUE THREAD

**Issue by ser** [slashbeast/better-initramfs#45]
It's a really cool useful project, are you planning PPA for ubuntu by any chance?

**Comment by slashbeast** [comment]
binit does not support any sort of loadable kernel modules, that are quite common with kernels like Ubuntu have, it would require a lot of boilerplate to handle the initramfs update hooks etc, so unlikely, unless someone contribute them actually.

**Comment by slashbeast** [comment]
Since I hardly have idea how to PPA it I will close it, please reopen if you have any idea for it.
