### ISSUE TITLE
Fail to build (/dev/null: Permission denied)

### ISSUE THREAD

**Issue by travankor** [slashbeast/better-initramfs#47]
I type `sudo make bootstrap-all`, and this fails because of `/dev/null: Permission denied`. Any idea of what I am doing wrong?

https://gist.github.com/travankor/07f8bcaab21fbe17f852ab7b64e5ac8f

I'm not sure if it is permissions related.

```
[Travankor build_dir]$ ls -ld dev
drwxr-xr-x 2 travankor users 4096 Aug  3 20:35 dev
[Travankor build_dir]$ cd dev
[Travankor dev]$ ls -l 
total 0
crw-rw-rw- 1 root root 1, 3 Aug  3 20:35 null
crw-rw-rw- 1 root root 1, 8 Aug  3 20:35 random
crw-rw-rw- 1 root root 1, 9 Aug  3 20:35 urandom
crw-rw-rw- 1 root root 1, 5 Aug  3 20:35 zero
```

**Comment by slashbeast** [comment]
Unless you have some fancy GRSEC, SELinux or such, I would suspect your /home mountpoint being mounted with 'nodev' option. If it's the case, try:

    mount -o remount,dev /home

As root, and then it should work.

On todo list I actually have a item to make it buildable with bubblewrap, wich would no longer require root to do so (but user_ns), so in future it will be slightly better.

**Comment by travankor** [comment]
Yep, that fixed it. Thanks for responding so soon.
